branches:
  only:
  - master

language: php node_js

sudo: false

php:
  - "5.5"

node_js:
  - "5.9"


before_script:
  - phpenv global 5.5
  - php --version
  - composer --version
  - nvm install 5.9
  - node --version
  - npm --version
  - nvm --version
  - PROJECT_BASE="`pwd`"
  - cd "$PROJECT_BASE/dynamic"
  - cp .env.example .env
  - composer self-update
  - composer install
  - cd "$PROJECT_BASE/static"
  - cp .env.example .env
  - npm install -g gulp gulp-cli typescript less
  - npm install
  - npm install
  - npm link typescript

script:
  - cd "$PROJECT_BASE/static"
  - npm run build
  - npm run test

