branches:
  only:
  - master

language: node_js

sudo: false

node_js:
  - '5.9'

install:
  - PROJECT_BASE="`pwd`"
  - cd "$PROJECT_BASE/dynamic"
  - cp .env.example .env
  - composer install
  - cd "$PROJECT_BASE/static"
  - cp .env.example .env
  - npm install -g gulp gulp-cli typescript less
  - npm install
  - npm install
  - npm link typescript

script:
  - cd "$PROJECT_BASE/static"
  - npm run build
  - npm run test

