branches:
  only:
  - master

language: php

sudo: false

php:
  - "5.5"

node_js:
  - "5.9"


before_script:
  - nvm install 5.9
  - node --version
  - npm --version
  - nvm --version
  - PROJECT_BASE="`pwd`"
  - cd "$PROJECT_BASE/dynamic"
  - cp .env.example .env
  - composer self-update
  - composer install
  - cd "$PROJECT_BASE/static"
  - cp .env.example .env
  - npm install
  - ln -s `pwd`/src node_modules/app

script:
  - cd "$PROJECT_BASE/static"
  - npm run build
  - npm run test

after_script:
  - cd "$PROJECT_BASE"
  - tree static/typings
  - cat dynamic/bootstrap/cache/*.php
  - cat static/public/*.json
  - cat static/public/*.js
  - cat static/*.log


